### PR TITLE
Upgrade to Bootstrap3

### PR DESCRIPTION
**Pull request by dashohoxha**
We can merge this later, after fixing CSS issues etc.

### CODE REVIEW

**Comment by dashohoxha** [comment]
Testing:

    git clone --branch=labdoo3 https://github.com/Labdoo/Labdoo
    mkdir test/
    cd test/
    ln -s ../Labdoo/docker .
    docker/build.sh
    docker/create.sh
    docker/start.sh
    docker/enter.sh

**Comment by dashohoxha** [comment]
It is possible to include `.css.less` files, as well as `.css` (with `drupal_add_css()`), and they will be converted automatically to css. Don't forget to clear the cashe: `drush cc css-js; drush cc less`.

**Comment by dashohoxha** [comment]
I just tried `utils/docker-install.sh`. It worked well for me.

**Comment by jrosgiralt** [comment]
Good job Dashamir. I'm working implementing a couple of tickets opened by a user and after that i will  have some time to test your docker installation.

**Comment by dashohoxha** [comment]
https://github.com/docker-build/dbox is deprecated and is replaced by https://github.com/docker-scripts/dbox

**Pull request closed without merging**
